// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

public interface ArrayDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ArrayData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 data = 1;</code>
   * @return A list containing the data.
   */
  java.util.List<java.lang.Integer> getDataList();
  /**
   * <code>repeated int32 data = 1;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <code>repeated int32 data = 1;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  int getData(int index);
}
